# This workflow will install Python dependencies, run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unittest packages

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: '1.7'
    - name: Julia build
      uses: julia-actions/julia-buildpkg@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        curl -sSL https://install.python-poetry.org | python3 -
        poetry config virtualenvs.create false
        poetry install --no-root
        poetry run python -c "import julia; julia.install()"
    - name: Unitest with coverage
      run: |
        poetry run pytest -v --cov=src/ -m 'not cplex'
        julia --project -e 'using Pkg;Pkg.test()'
