# This workflow will install Python dependencies, run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unittest packages

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        julia-version: ["1.7"]

    steps:
    - name: Checkout branch
      uses: actions/checkout@v2
    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      with:
        version: ${{ matrix.julia-version }}
    - name: Julia build
      uses: julia-actions/julia-buildpkg@v1
    - name: Unitest with coverage
      run: |
        julia --project -e 'using Pkg;Pkg.test()'
